NUMERO1 = float(INPUT(DIGITE O PRIMEIRO NUMERO ))
OPERADOR = float("DIGITE O OPERADOR(+-/*)")"
NUMERO2 = float(INPUT("DIGITE O SEGUNDO NUMERO "))

IF OPERADOR == "+":
print(" RESULTADO: ", NUMERO1 + NUMERO2)

ELIF OPERADOR == "-":
print(" RESULTADO: ", NUMERO1 - NUMERO2)


ELIF OPERADOR == "/":
IF NUMERO2 != 0
print("RESULTADO: ", NUMERO1 / NUMERO2)
ELSE:
print(ERRO: DIVISÃO POR ZERO NÃO EXISTE )
ELSE:
print("Erro: Operador invalido")


ELIF OPERADOR == "*":
print(" RESULTADO: ", NUMERO1 * NUMERO2)

